require("include/nexorix")

require("gamemode/modulos/core/config")
require("gamemode/modulos/database/database")

require("gamemode/modulos/auth/auth")
require("gamemode/modulos/core/player")
require("gamemode/modulos/admin/admin")
require("gamemode/modulos/admin/commands")
require("gamemode/modulos/orgs/orgs")
require("gamemode/modulos/orgs/commands-orgs")
require("gamemode/modulos/commands/commands")
require("gamemode/modulos/hud/hud")
require("gamemode/modulos/maps/drop")
require("gamemode/modulos/bot/bot")

NX.Hook("OnGameModeInit", function()
    nx_DisableInteriorEnterExits()
    nx_SetGameModeText(SERVER_CONFIG.Name .. " " .. SERVER_CONFIG.Version)
    nx_print("------------------------------------------")
    nx_print(" " .. SERVER_CONFIG.Name .. " v" .. SERVER_CONFIG.Version)
    nx_print(" Modulos carregados com sucesso!")
    nx_print("------------------------------------------")
end)
